version: '3.9'

services:
  app:
    image: my-cab-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - TZ=Asia/Kolkata  

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"

volumes:
  mongo-data:
